PACKAGE_NAME="fte3600"
PACKAGE_VERSION="0.1"
BUILT_MODULE_NAME[0]="fte3600"
BUILT_MODULE_LOCATION[0]="kernel/fte3600"
DEST_MODULE_LOCATION[0]="/kernel/drivers/spi"
MAKE[0]="make -C kernel/fte3600 KDIR=/lib/modules/${kernelver}/build"
CLEAN="make -C kernel/fte3600 KDIR=/lib/modules/${kernelver}/build clean"
AUTOINSTALL="yes"
