/*
 * Firmware loader tests using ordinary generated bytes, never vendor payloads
 *
 * Copyright (C) 2026 FTE3600 Linux contributors
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

#include <errno.h>
#include <fcntl.h>
#include <glib/gstdio.h>
#include <sys/stat.h>
#include <unistd.h>

#include "drivers/fte3600-firmware.h"

typedef enum {
  READ_NORMAL,
  READ_INTERRUPTED,
  READ_SHORT,
  READ_ERROR,
  READ_GROW,
  READ_SHRINK,
  READ_CHANGE,
} ReadBehavior;

typedef struct
{
  gchar          *directory;
  gchar          *path;
  gchar          *digest;
  guint8          payload[257];
  Fte3600Firmware firmware;
} Fixture;

static ReadBehavior read_behavior;
static const gchar *mutation_path;
static gint last_read_fd = -1;
static gsize largest_read_request;

ssize_t __real_read (int    fd,
                     void  *buffer,
                     size_t count);
ssize_t __wrap_read (int    fd,
                     void  *buffer,
                     size_t count);
#ifdef __GLIBC__
ssize_t __real___read_chk (int    fd,
                           void  *buffer,
                           size_t count,
                           size_t buffer_length);
ssize_t __wrap___read_chk (int    fd,
                           void  *buffer,
                           size_t count,
                           size_t buffer_length);
#endif

typedef ssize_t (*ReadFunction) (int    fd,
                                 void  *buffer,
                                 size_t count,
                                 size_t buffer_length);

static ssize_t
read_with_injection (int fd, void *buffer, size_t count, size_t buffer_length,
                     ReadFunction read_function)
{
  ReadBehavior behavior = read_behavior;

  last_read_fd = fd;
  largest_read_request = MAX (largest_read_request, count);
  if (behavior != READ_SHORT)
    read_behavior = READ_NORMAL;

  if (behavior == READ_INTERRUPTED || behavior == READ_ERROR)
    {
      /* After the interruption, also exercise repeated short reads. */
      if (behavior == READ_INTERRUPTED)
        read_behavior = READ_SHORT;
      errno = behavior == READ_INTERRUPTED ? EINTR : EIO;
      return -1;
    }

  if (behavior == READ_GROW || behavior == READ_SHRINK || behavior == READ_CHANGE)
    {
      gint mutation_fd = open (mutation_path, O_WRONLY | O_CLOEXEC);
      guint8 byte = 0xa5;

      g_assert_cmpint (mutation_fd, >=, 0);
      if (behavior == READ_GROW)
        {
          g_assert_cmpint (lseek (mutation_fd, 0, SEEK_END), >=, 0);
          g_assert_cmpint (write (mutation_fd, &byte, 1), ==, 1);
        }
      else if (behavior == READ_SHRINK)
        {
          g_assert_cmpint (ftruncate (mutation_fd, 0), ==, 0);
        }
      else
        {
          g_assert_cmpint (write (mutation_fd, &byte, 1), ==, 1);
        }
      g_assert_cmpint (close (mutation_fd), ==, 0);
    }

  return read_function (fd, buffer, behavior == READ_SHORT ? MIN (count, 3) : count,
                        buffer_length);
}

static ssize_t
read_unfortified (int fd, void *buffer, size_t count, size_t buffer_length)
{
  (void) buffer_length;
  return __real_read (fd, buffer, count);
}

ssize_t
__wrap_read (int fd, void *buffer, size_t count)
{
  return read_with_injection (fd, buffer, count, G_MAXSIZE, read_unfortified);
}

#ifdef __GLIBC__
ssize_t
__wrap___read_chk (int fd, void *buffer, size_t count, size_t buffer_length)
{
  /* Optimized glibc builds retain the actual fortified read, including its
   * bounds check. Check the original request before a short-read injection. */
  g_assert_cmpuint (count, <=, buffer_length);
  return read_with_injection (fd, buffer, count, buffer_length, __real___read_chk);
}
#endif

static void
fixture_setup (Fixture *fixture, gconstpointer data)
{
  g_autoptr(GError) error = NULL;

  (void) data;
  fixture->directory = g_dir_make_tmp ("fte3600-firmware-test-XXXXXX", &error);
  g_assert_no_error (error);
  fixture->path = g_build_filename (fixture->directory, "payload.bin", NULL);
  for (gsize i = 0; i < G_N_ELEMENTS (fixture->payload); i++)
    fixture->payload[i] = (i * 73 + 19) % 251;
  fixture->digest = g_compute_checksum_for_data (G_CHECKSUM_SHA256,
                                                 fixture->payload, sizeof fixture->payload);
  fixture->firmware = (Fte3600Firmware){
    .role = FTE3600_FIRMWARE_APPLICATION,
    .filename = "test/payload.bin",
    .size = sizeof fixture->payload,
    .sha256 = fixture->digest,
  };
  g_assert_true (g_file_set_contents (fixture->path, (const gchar *) fixture->payload,
                                      sizeof fixture->payload, &error));
  g_assert_no_error (error);
  read_behavior = READ_NORMAL;
  mutation_path = fixture->path;
  last_read_fd = -1;
  largest_read_request = 0;
}

static void
fixture_teardown (Fixture *fixture, gconstpointer data)
{
  (void) data;
  if (last_read_fd >= 0)
    {
      errno = 0;
      g_assert_cmpint (fcntl (last_read_fd, F_GETFD), ==, -1);
      g_assert_cmpint (errno, ==, EBADF);
      g_assert_cmpuint (largest_read_request, <=, sizeof fixture->payload + 1);
    }
  g_assert_cmpint (g_unlink (fixture->path), ==, 0);
  g_assert_cmpint (g_rmdir (fixture->directory), ==, 0);
  g_free (fixture->digest);
  g_free (fixture->path);
  g_free (fixture->directory);
  read_behavior = READ_NORMAL;
  mutation_path = NULL;
}

static void
assert_load_success (Fixture *fixture)
{
  g_autoptr(GError) error = NULL;
  g_autoptr(GBytes) bytes = fpi_fte3600_firmware_load (&fixture->firmware, fixture->path, &error);

  g_assert_no_error (error);
  g_assert_nonnull (bytes);
  g_assert_cmpmem (g_bytes_get_data (bytes, NULL), g_bytes_get_size (bytes),
                   fixture->payload, sizeof fixture->payload);
}

static void
test_valid (Fixture *fixture, gconstpointer data)
{
  (void) data;
  assert_load_success (fixture);
}

static void
test_uppercase_digest (Fixture *fixture, gconstpointer data)
{
  g_autofree gchar *uppercase = g_ascii_strup (fixture->digest, -1);

  (void) data;
  fixture->firmware.sha256 = uppercase;
  assert_load_success (fixture);
}

static void
test_wrong_digest (Fixture *fixture, gconstpointer data)
{
  g_autoptr(GError) error = NULL;
  g_autoptr(GBytes) bytes = NULL;

  (void) data;
  fixture->digest[0] = fixture->digest[0] == '0' ? '1' : '0';
  bytes = fpi_fte3600_firmware_load (&fixture->firmware, fixture->path, &error);
  g_assert_null (bytes);
  g_assert_error (error, G_IO_ERROR, G_IO_ERROR_INVALID_DATA);
}

static void
test_wrong_size (Fixture *fixture, gconstpointer data)
{
  g_autoptr(GError) error = NULL;
  g_autoptr(GBytes) bytes = NULL;

  fixture->firmware.size += GPOINTER_TO_INT (data);
  bytes = fpi_fte3600_firmware_load (&fixture->firmware, fixture->path, &error);
  g_assert_null (bytes);
  g_assert_error (error, G_IO_ERROR, G_IO_ERROR_INVALID_DATA);
}

static void
assert_invalid_arguments (const Fte3600Firmware *firmware, const gchar *path)
{
  g_autoptr(GError) error = NULL;
  g_autoptr(GBytes) bytes = fpi_fte3600_firmware_load (firmware, path, &error);

  g_assert_null (bytes);
  g_assert_error (error, G_IO_ERROR, G_IO_ERROR_INVALID_ARGUMENT);
}

static void
test_invalid_metadata (Fixture *fixture, gconstpointer data)
{
  Fte3600Firmware invalid = fixture->firmware;

  (void) data;
  assert_invalid_arguments (NULL, fixture->path);
  assert_invalid_arguments (&invalid, NULL);
  assert_invalid_arguments (&invalid, "");
  invalid.size = 0;
  assert_invalid_arguments (&invalid, fixture->path);
  invalid.size = FTE3600_FIRMWARE_MAX_SIZE + 1;
  assert_invalid_arguments (&invalid, fixture->path);
  invalid.size = G_MAXSIZE;
  assert_invalid_arguments (&invalid, fixture->path);
  invalid = fixture->firmware;
  invalid.sha256 = NULL;
  assert_invalid_arguments (&invalid, fixture->path);
  invalid.sha256 = "";
  assert_invalid_arguments (&invalid, fixture->path);
  invalid.sha256 = "0123456789abcdef";
  assert_invalid_arguments (&invalid, fixture->path);
  invalid.sha256 = "z123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";
  assert_invalid_arguments (&invalid, fixture->path);
  g_assert_cmpint (last_read_fd, ==, -1);
}

static void
test_missing (Fixture *fixture, gconstpointer data)
{
  g_autofree gchar *path = g_build_filename (fixture->directory, "missing.bin", NULL);

  g_autoptr(GError) error = NULL;
  g_autoptr(GBytes) bytes = fpi_fte3600_firmware_load (&fixture->firmware, path, &error);

  (void) data;
  g_assert_null (bytes);
  g_assert_error (error, G_IO_ERROR, G_IO_ERROR_NOT_FOUND);
}

static void
test_directory (Fixture *fixture, gconstpointer data)
{
  g_autoptr(GError) error = NULL;
  g_autoptr(GBytes) bytes = fpi_fte3600_firmware_load (&fixture->firmware,
                                                       fixture->directory, &error);

  (void) data;
  g_assert_null (bytes);
  g_assert_error (error, G_IO_ERROR, G_IO_ERROR_INVALID_DATA);
}

static void
test_fifo (Fixture *fixture, gconstpointer data)
{
  g_autofree gchar *path = g_build_filename (fixture->directory, "fifo", NULL);

  g_autoptr(GError) error = NULL;
  g_autoptr(GBytes) bytes = NULL;

  (void) data;
  g_assert_cmpint (mkfifo (path, 0600), ==, 0);
  bytes = fpi_fte3600_firmware_load (&fixture->firmware, path, &error);
  g_assert_null (bytes);
  g_assert_error (error, G_IO_ERROR, G_IO_ERROR_INVALID_DATA);
  g_assert_cmpint (g_unlink (path), ==, 0);
}

static void
test_symlink_to_regular_file (Fixture *fixture, gconstpointer data)
{
  g_autofree gchar *path = g_build_filename (fixture->directory, "linked.bin", NULL);

  g_autoptr(GError) error = NULL;
  g_autoptr(GBytes) bytes = NULL;

  (void) data;
  g_assert_cmpint (symlink (fixture->path, path), ==, 0);
  bytes = fpi_fte3600_firmware_load (&fixture->firmware, path, &error);
  g_assert_no_error (error);
  g_assert_nonnull (bytes);
  g_assert_cmpmem (g_bytes_get_data (bytes, NULL), g_bytes_get_size (bytes),
                   fixture->payload, sizeof fixture->payload);
  g_assert_cmpint (g_unlink (path), ==, 0);
}

static void
test_interruption_and_short_reads (Fixture *fixture, gconstpointer data)
{
  (void) data;
  read_behavior = READ_INTERRUPTED;
  assert_load_success (fixture);
  g_assert_cmpint (read_behavior, ==, READ_SHORT);
}

static void
test_read_error (Fixture *fixture, gconstpointer data)
{
  g_autoptr(GError) error = NULL;
  g_autoptr(GBytes) bytes = NULL;

  (void) data;
  read_behavior = READ_ERROR;
  bytes = fpi_fte3600_firmware_load (&fixture->firmware, fixture->path, &error);
  g_assert_null (bytes);
  g_assert_error (error, G_IO_ERROR, (gint) g_io_error_from_errno (EIO));
}

static void
test_concurrent_change (Fixture *fixture, gconstpointer data)
{
  g_autoptr(GError) error = NULL;
  g_autoptr(GBytes) bytes = NULL;

  read_behavior = GPOINTER_TO_INT (data);
  bytes = fpi_fte3600_firmware_load (&fixture->firmware, fixture->path, &error);
  g_assert_null (bytes);
  g_assert_error (error, G_IO_ERROR, G_IO_ERROR_INVALID_DATA);
  g_assert_cmpint (read_behavior, ==, READ_NORMAL);
}

int
main (int argc, char **argv)
{
  g_test_init (&argc, &argv, NULL);
  g_test_add ("/fte3600/firmware/valid", Fixture, NULL,
              fixture_setup, test_valid, fixture_teardown);
  g_test_add ("/fte3600/firmware/uppercase-digest", Fixture, NULL,
              fixture_setup, test_uppercase_digest, fixture_teardown);
  g_test_add ("/fte3600/firmware/wrong-digest", Fixture, NULL,
              fixture_setup, test_wrong_digest, fixture_teardown);
  g_test_add ("/fte3600/firmware/size-short", Fixture, GINT_TO_POINTER (-1),
              fixture_setup, test_wrong_size, fixture_teardown);
  g_test_add ("/fte3600/firmware/size-long", Fixture, GINT_TO_POINTER (1),
              fixture_setup, test_wrong_size, fixture_teardown);
  g_test_add ("/fte3600/firmware/invalid-metadata", Fixture, NULL,
              fixture_setup, test_invalid_metadata, fixture_teardown);
  g_test_add ("/fte3600/firmware/missing", Fixture, NULL,
              fixture_setup, test_missing, fixture_teardown);
  g_test_add ("/fte3600/firmware/directory", Fixture, NULL,
              fixture_setup, test_directory, fixture_teardown);
  g_test_add ("/fte3600/firmware/fifo", Fixture, NULL,
              fixture_setup, test_fifo, fixture_teardown);
  g_test_add ("/fte3600/firmware/symlink", Fixture, NULL,
              fixture_setup, test_symlink_to_regular_file, fixture_teardown);
  g_test_add ("/fte3600/firmware/interrupted-short-read", Fixture, NULL,
              fixture_setup, test_interruption_and_short_reads, fixture_teardown);
  g_test_add ("/fte3600/firmware/read-error", Fixture, NULL,
              fixture_setup, test_read_error, fixture_teardown);
  g_test_add ("/fte3600/firmware/concurrent-grow", Fixture, GINT_TO_POINTER (READ_GROW),
              fixture_setup, test_concurrent_change, fixture_teardown);
  g_test_add ("/fte3600/firmware/concurrent-shrink", Fixture, GINT_TO_POINTER (READ_SHRINK),
              fixture_setup, test_concurrent_change, fixture_teardown);
  g_test_add ("/fte3600/firmware/concurrent-change", Fixture, GINT_TO_POINTER (READ_CHANGE),
              fixture_setup, test_concurrent_change, fixture_teardown);
  return g_test_run ();
}
